    catch(char* err){
        cout << "エラー:" << err << endl;
        return 1;
    }